### PR TITLE
feat(editor): Ability to Pass Optional Line Number Argument to `Cmd`

### PR DESCRIPTION
**Pull request by h0rv**
This is needed for a feature I want to implement in Glow: https://github.com/charmbracelet/glow/issues/547.

### CODE REVIEW

**Comment by h0rv** [comment]
Hi @meowgorithm, would you mind reviewing this PR when you get a change? Thanks!

**Comment by caarlos0** [comment]
maybe instead we pass a `lineNumber` arg, and handle it here? so it can be used in other projects as well

**Comment by h0rv** [comment]
Ok I have logic in a local Charm PR to add this. Right now, I know for certain that `nano`, `vi`, `vim`, and `nvim` support this feature.

And how about leaving the current change being able to pass in arbitrary args, and then creating a new function a new function: `openEditorAtLine`?

**Comment by caarlos0** [comment]
I think we can leave it out unless we find a good use case for it 🤔

**Comment by h0rv** [comment]
Updated to only include `lineNumber`

**Comment by caarlos0** [comment]
see  #26

**Pull request merged**
