### PR TITLE
fix: set cursor style sequence

### PR DESCRIPTION
**Pull request by caarlos0**
extra space :)

### CODE REVIEW

**Review by aymanbagabas — APPROVED** [review]
Good catch!

**Comment by aymanbagabas** [comment]
Whoops, we should revert this

**Comment by aymanbagabas** [comment]
> ohhhh right... so the parser is not dealing with this properly then?

The handler was invalid, opened a PR

**Comment by caarlos0** [comment]
i realized it was missing the ' ' intermediate shift instantly after i commented :kek:

**Pull request merged**
